### ISSUE TITLE
Deploy ZORALab's Hestia

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/demo-web-prestige#1]
Get the initialization done quick. We modify it to match the prestige protoype.

**Comment by corygalyna** [comment]
What is this about again?

**Comment by hollowaykeanho** [comment]
A potential client requesting a design prototype so let's deploy Hestia to demonstrate it.

**Comment by corygalyna** [comment]
OK... on it.

**Comment by corygalyna** [comment]
But get this repo up ASAP. It's too crude.

**Comment by hollowaykeanho** [comment]
All right. It's up. You can begin the project planning. Deadline is today, latest tomorrow 2pm (MY) for the project to complete entirely.

**Comment by corygalyna** [comment]
That rush?! No time for Kanban board then. You focus on the GUI re-development part. I will work on the content writing.

**Comment by hollowaykeanho** [comment]
Released in version `v1.0.0`.
