### ISSUE TITLE
Strengthen Offline Assets Capabilities

### ISSUE THREAD

**Issue by corygalyna** [ZORALab/demo-web-prestige#31]
# Description
```
Please provide a short description of what feature you're looking forward to
add into the existing repository below. Please include the story behind your
idea as well to give a better visualization of your idea.
```
Right now, the landing page offline capability is neglected so we have to strengthen it once we completed the overall landing page design. For now, this ticket tracks the progress.

Requires Issue #24 and other similar items to be completed.

# Expected Behavior
```
Please specify the expected behavior of your requested feature. Some great and
helpful pointers are your expected interface (e.g. command patterns, simple
sketches of the user interface, etc).
```
Offline capability is fully empowered.

# Current Absent Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
Offline capability is partially empowered.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
Delivered in 444f667e1d54f77cc4ec45095ba308669142e16a
