### ISSUE TITLE
Choose A Better Font

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/demo-web-prestige#38]
# Description
```
Please provide a short description of what feature you're looking forward to
enhance below. Please include the story behind your idea as well to give a
better visualization of your idea.
```
The site design looks slightly boring (however, Sibert disagreed and his specified is more of the content presentation itself like wording simplications and etc). He did mentions to choose a more modern sans-serif font rather than serif ones which can increase the "liveness" of the page.

# Expected Behavior
```
Please specify the expected behavior of your requested enhancement. Some great
and helpful pointers are your expected interface (e.g. command patterns,
simple sketches of the user interface, etc).
```
New font selected.

# Current Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
A bit ....boring impression.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
@corygalyna , you mind?

**Comment by corygalyna** [comment]
Sorry... was working on my side. This? https://fonts.google.com/specimen/Anek+Bangla?category=Sans+Serif

**Comment by hollowaykeanho** [comment]
Nope. I reused Noto Sans for body while retaining the existing font for headers. Looks very good now.

**Comment by hollowaykeanho** [comment]
ID: 01095347853133d47d6cb2ebfbb4cb66a0104d97
