### ISSUE TITLE
Develop corygalynaPROFILE component

### ISSUE THREAD

**Issue by corygalyna** [ZORALab/demo-web-prestige#44]
# Description
```
Please provide a short description of what feature you're looking forward to
add into the existing repository below. Please include the story behind your
idea as well to give a better visualization of your idea.
```
We need an UI component to present a user profile in team section. Let's make this component. Horizontal name tag please, not vertical. Hestia got too many vertical designs.

# Expected Behavior
```
Please specify the expected behavior of your requested feature. Some great and
helpful pointers are your expected interface (e.g. command patterns, simple
sketches of the user interface, etc).
```
a horizontal styled entity representing profile UI component is readily available for use.

# Current Absent Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
No such component is available.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
Done in 3ee03c2aba23f0ac80ec54b223d89c143fb75233
