### ISSUE TITLE
Fix The Landing Page's CTA section

### ISSUE THREAD

**Issue by corygalyna** [ZORALab/demo-web-prestige#45]
# Description
```
Please provide a short description of what you have encountered below.
```
The CTA section is not clear. What exactly we want our visitor to do on this page? Go straight for get a quote from us via email or telegram you.

# Expected Behavior
```
Please specify the expected behavior of your usage below.
```
A clear CTA section.

# Current Behavior
```
Please specify the current behavior of software below.
```
CTA is unclear.

# Steps to Reproduce (COMPULSORY)
```
Please specify all the steps required to re-produce the problem.
```

# Attachments
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
Sibert also mentions about this as well. Prioritizing this one.

**Comment by hollowaykeanho** [comment]
Done: 1df6ce2cc8ff039d15660279222db37849f9416f
