### ISSUE TITLE
Refactor Entire Page's Wording and Contents - Make It Non-Tech People Friendly

### ISSUE THREAD

**Issue by corygalyna** [ZORALab/demo-web-prestige#46]
# Description
```
Please provide a short description of what feature you're looking forward to
enhance below. Please include the story behind your idea as well to give a
better visualization of your idea.
```
No ordinary folks understand the tech jargon. They feel stressed. Please re-word / refactor the entire content 1 last time before Monday and make it very friendly to non-tech individuals.

# Expected Behavior
```
Please specify the expected behavior of your requested enhancement. Some great
and helpful pointers are your expected interface (e.g. command patterns,
simple sketches of the user interface, etc).
```
Sentences and word crafting are done in the simplest way.

# Current Behavior
```
Please specify the current behavior (e.g. workaround, blockage, etc).
```
Very tech oriented. It's not friendly to non-tech folks.

# Attachment
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment]
first iteration: 0f8d9923452fbd6980423900c7d5f78ee69e6be1

**Comment by hollowaykeanho** [comment]
Passed granny test. All acronyms are now replaced: 3d787eb2141dfd442beb6bfb86c2ea80805fe015

Will ship this feature for now. Too risky to alter more stuffs.
